select * from tiempo;
select * from elemento;
select * from producto;
select * from pais_declarante;
select * from pais_socio;
select * from sub_continentes_declarante;
select * from sub_continentes_socio;
select * from continentes_declarante;
select * from continentes_socio;